//! The generator of statements, per document 14 section 14.7 of the notes.
//!
//! One seed gives one SQL file, `run/gen/seed-<n>.sql`, and the differential runner runs it on
//! both servers in its three modes. The file has four parts:
//!
//! - The values: each edge value of document 06 section 6.16 cast to its type, again under each
//!   value of the settings that change the output, and some strings that the input function
//!   must refuse.
//! - The functions: calls to each immutable function and aggregate of `pg_catalog`, read from
//!   the catalog of the oracle, with edge values of the argument types.
//! - The schema: three tables with random rows.
//! - The queries: random queries over the schema, in the manner of SQLsmith.
//!
//! After the file, the logic checks run on each server alone. They compare a query with a
//! partitioned form of it (TLP) or with a form that the optimizer cannot change (NoREC), in the
//! manner of SQLancer. A check needs no oracle, so it finds wrong answers where both servers
//! would agree with a wrong plan. A check where either query fails is not counted.
//!
//! The harness has no dependencies, so the generators are written here and do not come from
//! `rudb-compat`. The walk over the grammar productions waits for the vendored grammar of
//! document 08.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::client::{self, Client, Login};
use crate::diff;
use crate::frame::Frame;
use crate::json::Json;
use crate::servers::Server;

#[derive(Debug, Clone)]
pub(crate) struct Options {
    pub(crate) seed: u64,
    /// The number of random queries, and the number of logic checks.
    pub(crate) count: usize,
}

/// The database of the logic checks. It is made again from `template0` before each run.
const DATABASE: &str = "rudb_postgres_gen";

/// The most calls for one function. The first call uses the first value of each type, and the
/// others are random.
const CALLS: usize = 3;

/// Generates the file of one seed, runs it through the differential runner and runs the logic
/// checks. Returns the number of statements that differ plus the number of failed checks.
pub(crate) fn run(
    root: &Path,
    oracle: &Server,
    other: &Server,
    options: &Options,
) -> Result<(usize, Json), String> {
    println!("seed {}", options.seed);
    let mut rng = Rng::new(options.seed);
    let functions = functions(oracle)?;
    let schema = schema(&mut rng);

    let mut file = String::new();
    let _ = writeln!(file, "-- Generated by rudb-postgres gen --seed {}.", options.seed);
    file.push_str("set statement_timeout = '10s';\n");
    let values = write_values(&mut file);
    let calls = write_calls(&mut file, &functions, &mut rng);
    file.push_str("\n-- The schema of the queries.\n");
    for statement in &schema {
        let _ = writeln!(file, "{statement};");
    }
    file.push_str("\n-- The queries.\n");
    for _ in 0..options.count {
        let _ = writeln!(file, "{};", query(&mut rng));
    }

    let dir = root.join("run").join("gen");
    std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    let path: PathBuf = dir.join(format!("seed-{}.sql", options.seed));
    std::fs::write(&path, &file).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    println!(
        "{} values, {calls} calls of {} functions, {} queries",
        values,
        functions.len(),
        options.count
    );
    let (differ, diff_json) = diff::run(&path, oracle, other, &diff::Options { rpg: false })?;

    let checks = checks(&mut rng, options.count);
    let mut failed = 0;
    let mut logic = Vec::new();
    for server in [oracle, other] {
        let (n, json) = run_checks(server, &schema, &checks)?;
        failed += n;
        logic.push(json);
    }

    let json = Json::object(vec![
        ("seed", Json::String(options.seed.to_string())),
        ("file", Json::String(path.display().to_string())),
        ("values", Json::Number(values as i64)),
        ("calls", Json::Number(calls as i64)),
        ("functions", Json::Number(functions.len() as i64)),
        ("queries", Json::Number(options.count as i64)),
        ("diff", diff_json),
        ("logic", Json::Array(logic)),
    ]);
    Ok((differ + failed, json))
}

/// SplitMix64. It is small, and the same seed gives the same file on every platform.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Rng {
        Rng(seed)
    }

    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }

    fn range(&mut self, low: i64, high: i64) -> i64 {
        low + (self.next() % (high - low + 1) as u64) as i64
    }

    fn chance(&mut self, percent: u64) -> bool {
        self.next() % 100 < percent
    }

    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        &items[self.below(items.len())]
    }
}

/// A string as an SQL literal.
fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// A type name that means the catalog type with no type modifier. Quoted, `bit` and `char`
/// are the catalog types, and not `bit(1)` and `char(1)`.
fn type_name(typname: &str) -> String {
    format!("pg_catalog.\"{}\"", typname.replace('"', "\"\""))
}

/// The edge values of each type, as the text that goes to the input function.
const VALUES: &[(&str, &[&str])] = &[
    ("bool", &["true", "false"]),
    ("int2", &["0", "1", "-1", "-32768", "32767"]),
    ("int4", &["1", "0", "-1", "-2147483648", "2147483647"]),
    ("int8", &["1", "0", "-1", "-9223372036854775808", "9223372036854775807"]),
    ("oid", &["0", "1", "4294967295"]),
    ("float4", &["1.5", "0", "-0", "3.4028235e38", "1e-45", "NaN", "Infinity", "-Infinity"]),
    (
        "float8",
        &["0.1", "0", "-0", "1.7976931348623157e308", "5e-324", "NaN", "Infinity", "-Infinity"],
    ),
    (
        "numeric",
        &[
            "1.5",
            "0",
            "-2.25",
            "123456789012345678901234567890.123456789",
            "0.000000000000000000001",
            "NaN",
            "Infinity",
            "-Infinity",
        ],
    ),
    ("text", &["abc", "", "a'b", " x ", "{a,\"b c\"}", "Ünï", "a\\b"]),
    ("varchar", &["abc", "", "a'b", " x "]),
    ("bpchar", &["abc", "", "a  "]),
    ("name", &["abc", "", "Ünï"]),
    ("cstring", &["1", "abc", ""]),
    ("char", &["a", ""]),
    ("bytea", &["\\x00ff", "\\x", "abc", "a\\\\b"]),
    (
        "date",
        &["2026-10-05", "2000-02-29", "4713-01-01 BC", "5874897-12-31", "infinity", "-infinity"],
    ),
    ("time", &["12:34:56.5", "00:00", "23:59:59.999999", "24:00:00"]),
    ("timetz", &["12:34+05:30", "00:00+00", "23:59:59.999999-15:59"]),
    (
        "timestamp",
        &[
            "2026-10-05 12:34:56",
            "2026-10-05 23:59:59.999999",
            "4713-01-01 00:00 BC",
            "294276-12-31 23:59:59.999999",
            "infinity",
            "-infinity",
        ],
    ),
    (
        "timestamptz",
        &[
            "2026-10-05 12:00+02",
            "1999-12-31 23:59:59.999999+14",
            "4713-01-01 00:00+00 BC",
            "infinity",
            "-infinity",
        ],
    ),
    (
        "interval",
        &[
            "1 year 2 mons 3 days 04:05:06.789",
            "0",
            "-1 day -00:00:01",
            "1 microsecond",
            "178000000 years",
            "infinity",
            "-infinity",
        ],
    ),
    (
        "uuid",
        &[
            "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            "00000000-0000-0000-0000-000000000000",
            "ffffffff-ffff-ffff-ffff-ffffffffffff",
        ],
    ),
    ("json", &["{\"a\": [1, 2.50, \"x\"]}", "null", "{}", "[]", "\"\\u00e9\"", "1e400"]),
    ("jsonb", &["{\"a\": [1, 2.50, \"x\"]}", "null", "{}", "[]", "\"\\u00e9\"", "1e400"]),
    ("inet", &["192.168.0.1/24", "0.0.0.0", "::1", "ffff::/16"]),
    ("cidr", &["192.168.0.0/24", "0.0.0.0/0", "::/0"]),
    ("macaddr", &["08:00:2b:01:02:03", "00:00:00:00:00:00", "ff:ff:ff:ff:ff:ff"]),
    ("macaddr8", &["08:00:2b:01:02:03:04:05", "00:00:00:00:00:00:00:00"]),
    ("money", &["1.5", "0", "-92233720368547758.08", "92233720368547758.07"]),
    ("bit", &["1010", "", "1"]),
    ("varbit", &["1010", "", "1"]),
    ("int4range", &["[1,5)", "empty", "(,)", "[-2147483648,2147483646]"]),
    ("int8range", &["[1,5)", "empty", "(,)"]),
    ("numrange", &["[1.5,2.5]", "empty", "(,)"]),
    ("daterange", &["[2026-01-01,2026-10-05)", "empty", "[2026-01-01,infinity)"]),
    ("tsrange", &["[\"2026-01-01 00:00\",\"2026-10-05 00:00\")", "empty", "(,)"]),
    ("tstzrange", &["[\"2026-01-01 00:00+00\",)", "empty"]),
    ("int4multirange", &["{[1,5), [7,9)}", "{}"]),
    ("point", &["(1.5,-2)", "(0,0)", "(NaN,Infinity)"]),
    ("lseg", &["[(0,0),(1,1)]"]),
    ("box", &["(1,1),(0,0)"]),
    ("path", &["[(0,0),(1,1),(2,0)]", "((0,0),(1,1))"]),
    ("polygon", &["((0,0),(1,0),(1,1))"]),
    ("circle", &["<(0,0),1>"]),
    ("line", &["{1,-1,0}"]),
    ("tsvector", &["a fat cat", "", "a:1A b:2"]),
    ("tsquery", &["a & b", "!a | (b <-> c)"]),
    ("pg_lsn", &["16/B374D848", "0/0", "FFFFFFFF/FFFFFFFF"]),
    ("int2vector", &["1 2", ""]),
    ("oidvector", &["1 2", ""]),
    ("_bool", &["{t,f,NULL}", "{}"]),
    ("_int2", &["{1,2}", "{}"]),
    ("_int4", &["{1,NULL,3}", "{}", "{{1,2},{3,4}}", "[0:1]={1,2}"]),
    ("_int8", &["{1,9223372036854775807}", "{}"]),
    ("_float8", &["{0.1,NaN,-0,Infinity}", "{}"]),
    ("_numeric", &["{1.5,NaN}", "{}"]),
    ("_text", &["{a,\"b c\",NULL,\"\\\"q\\\"\"}", "{}", "{\"\"}"]),
    ("_varchar", &["{a,b}", "{}"]),
    ("_name", &["{a,b}", "{}"]),
    ("_char", &["{a,b}", "{}"]),
    ("_bytea", &["{\"\\\\x00ff\"}", "{}"]),
    ("_date", &["{2026-10-05,infinity}", "{}"]),
    ("_timestamptz", &["{\"2026-10-05 12:00+02\"}", "{}"]),
    ("_interval", &["{\"1 day\"}", "{}"]),
    ("_jsonb", &["{\"{}\",\"[1]\"}", "{}"]),
    ("_float4", &["{1.5,NaN}", "{}"]),
    ("_oid", &["{1,2}", "{}"]),
];

/// The edge values of a type, or `None` when the generator has none for it.
fn values(typname: &str) -> Option<&'static [&'static str]> {
    VALUES.iter().find(|(t, _)| *t == typname).map(|(_, v)| *v)
}

/// The text types, where any string is valid input.
const TEXT_TYPES: &[&str] = &["text", "varchar", "bpchar", "name", "cstring", "char", "bytea"];

/// The settings that change how a value is written, and the types that each one changes.
const SETTINGS: &[(&str, &[&str], &[&str])] = &[
    (
        "DateStyle",
        &["ISO, MDY", "SQL, DMY", "Postgres, MDY", "German"],
        &["date", "timestamp", "timestamptz", "timetz", "interval", "_date"],
    ),
    (
        "IntervalStyle",
        &["postgres", "postgres_verbose", "sql_standard", "iso_8601"],
        &["interval", "_interval"],
    ),
    ("extra_float_digits", &["-15", "0", "1", "3"], &["float4", "float8", "_float8", "point"]),
    ("bytea_output", &["hex", "escape"], &["bytea", "_bytea"]),
];

/// Writes the values part and returns the number of statements in it.
fn write_values(file: &mut String) -> usize {
    let mut count = 0;
    file.push_str("\n-- The edge values of each type, and NULL.\n");
    for (typname, values) in VALUES {
        for v in values.iter() {
            let _ = writeln!(file, "select {}::{};", quote(v), type_name(typname));
            count += 1;
        }
        let _ = writeln!(file, "select NULL::{};", type_name(typname));
        count += 1;
    }
    file.push_str("\n-- Strings that the input function can refuse.\n");
    for (typname, _) in VALUES.iter().filter(|(t, _)| !TEXT_TYPES.contains(t)) {
        for bad in ["", "x", " 1 ", "9999999999999999999999"] {
            let _ = writeln!(file, "select {}::{};", quote(bad), type_name(typname));
            count += 1;
        }
    }
    file.push_str("\n-- The values again under each setting that changes the output.\n");
    for (setting, settings, types) in SETTINGS {
        for value in settings.iter() {
            let _ = writeln!(file, "set {setting} = {};", quote(value));
            count += 1;
            for typname in types.iter() {
                for v in values(typname).unwrap_or(&[]) {
                    let _ = writeln!(file, "select {}::{};", quote(v), type_name(typname));
                    count += 1;
                }
            }
        }
        let _ = writeln!(file, "reset {setting};");
        count += 1;
    }
    count
}

/// A function of `pg_catalog` that the generator calls.
#[derive(Debug)]
struct Function {
    name: String,
    args: Vec<String>,
    set: bool,
    variadic: bool,
}

/// Reads the immutable functions and aggregates of `pg_catalog` from the oracle, with the
/// names of their argument types.
fn functions(oracle: &Server) -> Result<Vec<Function>, String> {
    let sql = "\
select p.oid, p.proname, p.proretset, p.provariadic <> 0,
       coalesce((select string_agg(t.typname, ' ' order by u.n)
                 from unnest(p.proargtypes::oid[]) with ordinality u(o, n)
                 join pg_type t on t.oid = u.o), '')
from pg_proc p
where p.pronamespace = 'pg_catalog'::regnamespace and p.provolatile = 'i'
  and p.prokind in ('f', 'a') and p.prorettype <> 'internal'::regtype
order by p.oid";
    let mut admin =
        Client::connect(oracle, &Login::superuser("postgres")).map_err(|r| r.message)?;
    let reply = admin.simple(sql).map_err(|e| format!("{}: {e}", oracle.name))?;
    if let Some(error) = reply.iter().find(|f| f.tag == b'E') {
        return Err(format!("{}: {}", oracle.name, client::error_text(error)));
    }
    let mut functions = Vec::new();
    for row in client::rows(&reply) {
        let text = |i: usize| row.get(i).cloned().flatten().unwrap_or_default();
        let args: Vec<String> = text(4).split_whitespace().map(str::to_string).collect();
        if args.iter().all(|a| values(a).is_some()) {
            functions.push(Function {
                name: text(1),
                args,
                set: text(2) == "t",
                variadic: text(3) == "t",
            });
        }
    }
    Ok(functions)
}

/// Writes the calls and returns their number.
fn write_calls(file: &mut String, functions: &[Function], rng: &mut Rng) -> usize {
    let mut count = 0;
    file.push_str("\n-- Calls to the immutable functions and aggregates of pg_catalog.\n");
    for f in functions {
        let mut seen: Vec<String> = Vec::new();
        for call in 0..CALLS {
            let args: Vec<String> = f
                .args
                .iter()
                .enumerate()
                .map(|(i, typname)| {
                    let values = values(typname).unwrap_or(&[]);
                    let value = if call == 0 {
                        quote(values[0])
                    } else if rng.chance(15) {
                        "NULL".to_string()
                    } else {
                        quote(rng.pick(values))
                    };
                    let variadic =
                        if f.variadic && i + 1 == f.args.len() { "variadic " } else { "" };
                    format!("{variadic}{value}::{}", type_name(typname))
                })
                .collect();
            let args = args.join(", ");
            if seen.contains(&args) {
                continue;
            }
            let limit = if f.set { " limit 10" } else { "" };
            let name = f.name.replace('"', "\"\"");
            let _ = writeln!(file, "select pg_catalog.\"{name}\"({args}){limit};");
            seen.push(args);
            count += 1;
        }
    }
    count
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Ty {
    Int,
    Big,
    Num,
    Text,
    Bool,
    Date,
}

const TYPES: [Ty; 6] = [Ty::Int, Ty::Big, Ty::Num, Ty::Text, Ty::Bool, Ty::Date];

/// The columns of each table of the schema.
const COLUMNS: [(&str, Ty); 6] = [
    ("a", Ty::Int),
    ("b", Ty::Big),
    ("c", Ty::Num),
    ("e", Ty::Text),
    ("f", Ty::Bool),
    ("g", Ty::Date),
];

const TABLES: [&str; 3] = ["g1", "g2", "g3"];

/// A column that an expression can use, with the name of its table or alias.
#[derive(Debug, Clone)]
struct Column {
    table: String,
    name: String,
    ty: Ty,
}

fn columns(alias: &str) -> Vec<Column> {
    COLUMNS
        .iter()
        .map(|(name, ty)| Column { table: alias.to_string(), name: name.to_string(), ty: *ty })
        .collect()
}

/// The statements that make the tables and their rows. The values come from small sets, so
/// that joins and predicates match some rows and not all.
fn schema(rng: &mut Rng) -> Vec<String> {
    let mut statements = Vec::new();
    for table in TABLES {
        statements.push(format!(
            "create table {table} (a int4, b int8, c numeric, e text, f bool, g date)"
        ));
        let rows: Vec<String> = (0..rng.range(0, 24))
            .map(|_| {
                let values: Vec<String> =
                    COLUMNS.iter().map(|(_, ty)| row_value(rng, *ty)).collect();
                format!("({})", values.join(", "))
            })
            .collect();
        if !rows.is_empty() {
            statements.push(format!("insert into {table} values {}", rows.join(", ")));
        }
    }
    statements
}

fn row_value(rng: &mut Rng, ty: Ty) -> String {
    if rng.chance(15) {
        return "NULL".to_string();
    }
    match ty {
        Ty::Int => rng.range(-3, 10).to_string(),
        Ty::Big => (rng.range(-2, 5) * 1_000_000_000).to_string(),
        Ty::Num => rng.pick(&["0", "1.5", "-2.25", "10", "0.001", "123.456"]).to_string(),
        Ty::Text => quote(rng.pick(&["a", "b", "abc", "", "B", "a b", "x%y"])),
        Ty::Bool => rng.pick(&["true", "false"]).to_string(),
        Ty::Date => quote(rng.pick(&["2026-01-01", "2026-10-05", "1999-12-31", "2000-02-29"])),
    }
}

fn literal(rng: &mut Rng, ty: Ty) -> String {
    if rng.chance(5) {
        let name = match ty {
            Ty::Int => "int4",
            Ty::Big => "int8",
            Ty::Num => "numeric",
            Ty::Text => "text",
            Ty::Bool => "bool",
            Ty::Date => "date",
        };
        return format!("NULL::{name}");
    }
    match ty {
        Ty::Int => rng.range(-5, 12).to_string(),
        Ty::Big => format!("{}::int8", rng.range(-2, 5) * 1_000_000_000),
        Ty::Num => rng.pick(&["1.5", "-0.25", "0", "100.125"]).to_string(),
        Ty::Text => quote(rng.pick(&["a", "", "abc", "B", "b"])),
        Ty::Bool => rng.pick(&["true", "false"]).to_string(),
        Ty::Date => format!("date {}", quote(rng.pick(&["2026-10-05", "1999-12-31"]))),
    }
}

/// A random expression of a type over the columns in scope.
fn expr(rng: &mut Rng, scope: &[Column], ty: Ty, depth: u32) -> String {
    if depth == 0 || rng.chance(35) {
        let candidates: Vec<&Column> = scope.iter().filter(|c| c.ty == ty).collect();
        if !candidates.is_empty() && rng.chance(75) {
            let c = rng.pick(&candidates);
            return format!("{}.{}", c.table, c.name);
        }
        return literal(rng, ty);
    }
    let d = depth - 1;
    let e = |rng: &mut Rng, ty: Ty| expr(rng, scope, ty, d);
    match ty {
        Ty::Int => match rng.below(8) {
            0 => format!("({} + {})", e(rng, Ty::Int), e(rng, Ty::Int)),
            1 => format!("({} - {})", e(rng, Ty::Int), e(rng, Ty::Int)),
            2 => format!("abs({})", e(rng, Ty::Int)),
            3 => format!("({} % {})", e(rng, Ty::Int), rng.range(1, 7)),
            4 => format!("coalesce({}, {})", e(rng, Ty::Int), literal(rng, Ty::Int)),
            5 => format!(
                "case when {} then {} else {} end",
                e(rng, Ty::Bool),
                e(rng, Ty::Int),
                e(rng, Ty::Int)
            ),
            6 => format!("nullif({}, {})", e(rng, Ty::Int), literal(rng, Ty::Int)),
            _ => format!("length({})", e(rng, Ty::Text)),
        },
        Ty::Big => match rng.below(3) {
            0 => format!("({} + {})", e(rng, Ty::Big), e(rng, Ty::Big)),
            1 => format!("{}::int8", e(rng, Ty::Int)),
            _ => format!("coalesce({}, {})", e(rng, Ty::Big), literal(rng, Ty::Big)),
        },
        Ty::Num => match rng.below(6) {
            0 => format!("({} + {})", e(rng, Ty::Num), e(rng, Ty::Num)),
            1 => format!("({} - {})", e(rng, Ty::Num), e(rng, Ty::Num)),
            2 => format!("({} * {})", e(rng, Ty::Num), e(rng, Ty::Num)),
            3 => format!("round({}, 1)", e(rng, Ty::Num)),
            4 => format!("{}::numeric", e(rng, Ty::Int)),
            _ => format!("abs({})", e(rng, Ty::Num)),
        },
        Ty::Text => match rng.below(8) {
            0 => format!("({} || {})", e(rng, Ty::Text), e(rng, Ty::Text)),
            1 => format!("upper({})", e(rng, Ty::Text)),
            2 => format!("lower({})", e(rng, Ty::Text)),
            3 => format!("substr({}, 1, 2)", e(rng, Ty::Text)),
            4 => format!("coalesce({}, {})", e(rng, Ty::Text), literal(rng, Ty::Text)),
            5 => format!("{}::text", e(rng, Ty::Int)),
            6 => format!("trim({})", e(rng, Ty::Text)),
            _ => format!("replace({}, 'a', 'z')", e(rng, Ty::Text)),
        },
        Ty::Bool => {
            let t = *rng.pick(&[Ty::Int, Ty::Big, Ty::Num, Ty::Text, Ty::Date]);
            match rng.below(11) {
                0 | 1 => {
                    let op = rng.pick(&["=", "<>", "<", "<=", ">", ">="]);
                    format!("({} {op} {})", e(rng, t), e(rng, t))
                }
                2 => format!("({} is null)", e(rng, t)),
                3 => format!("({} is not null)", e(rng, t)),
                4 => format!("({} and {})", e(rng, Ty::Bool), e(rng, Ty::Bool)),
                5 => format!("({} or {})", e(rng, Ty::Bool), e(rng, Ty::Bool)),
                6 => format!("(not {})", e(rng, Ty::Bool)),
                7 => format!("({} between {} and {})", e(rng, t), e(rng, t), e(rng, t)),
                8 => format!("({} in ({}, {}))", e(rng, t), literal(rng, t), literal(rng, t)),
                9 => format!(
                    "({} like {})",
                    e(rng, Ty::Text),
                    quote(rng.pick(&["a%", "%b%", "_", "%", "a b"]))
                ),
                _ => format!("({} is distinct from {})", e(rng, t), e(rng, t)),
            }
        }
        Ty::Date => match rng.below(3) {
            0 => format!("({} + {})", e(rng, Ty::Date), rng.range(-3, 400)),
            1 => format!("coalesce({}, date '2026-01-01')", e(rng, Ty::Date)),
            _ => format!("greatest({}, {})", e(rng, Ty::Date), e(rng, Ty::Date)),
        },
    }
}

/// A select list of 1 to 4 expressions. Some have an alias and some keep the name that the
/// server gives them, because the column names are part of the answer.
fn select_list(rng: &mut Rng, scope: &[Column]) -> Vec<String> {
    (0..rng.range(1, 4))
        .map(|i| {
            let ty = *rng.pick(&TYPES);
            let e = expr(rng, scope, ty, 2);
            if rng.chance(50) { format!("{e} as c{}", i + 1) } else { e }
        })
        .collect()
}

fn aggregate(rng: &mut Rng, scope: &[Column]) -> String {
    let ty = *rng.pick(&TYPES);
    let e = expr(rng, scope, ty, 1);
    match ty {
        Ty::Int | Ty::Big | Ty::Num => {
            let f = rng.pick(&["count", "sum", "min", "max", "avg"]);
            format!("{f}({e})")
        }
        Ty::Text => match rng.below(4) {
            0 => format!("min({e})"),
            1 => format!("max({e})"),
            2 => format!("count(distinct {e})"),
            _ => format!("string_agg({e}, ',' order by {e})"),
        },
        Ty::Bool => format!("{}({e})", rng.pick(&["bool_and", "bool_or", "every", "count"])),
        Ty::Date => format!("{}({e})", rng.pick(&["min", "max"])),
    }
}

/// One random query over the schema.
fn query(rng: &mut Rng) -> String {
    let t1 = *rng.pick(&TABLES);
    let t2 = *rng.pick(&TABLES);
    let x = columns("x");
    let mut xy = columns("x");
    xy.extend(columns("y"));
    let where_ = |rng: &mut Rng, scope: &[Column]| {
        if rng.chance(70) {
            format!(" where {}", expr(rng, scope, Ty::Bool, 3))
        } else {
            String::new()
        }
    };
    match rng.below(8) {
        0 => {
            let list = select_list(rng, &x);
            format!("select {} from {t1} x{}", list.join(", "), where_(rng, &x))
        }
        1 => {
            let list = select_list(rng, &xy);
            let (kind, on) = match rng.below(4) {
                0 => ("join", format!("x.a = y.a and {}", expr(rng, &xy, Ty::Bool, 2))),
                1 => ("left join", expr(rng, &xy, Ty::Bool, 2)),
                2 => ("right join", "x.e = y.e".to_string()),
                _ => ("full join", "x.a = y.a".to_string()),
            };
            format!(
                "select {} from {t1} x {kind} {t2} y on {on}{}",
                list.join(", "),
                where_(rng, &xy)
            )
        }
        2 => {
            let keys: Vec<String> =
                (0..rng.range(1, 2)).map(|_| format!("x.{}", rng.pick(&COLUMNS).0)).collect();
            let mut list = keys.clone();
            for _ in 0..rng.range(1, 3) {
                list.push(aggregate(rng, &x));
            }
            let having = if rng.chance(30) {
                format!(" having count(*) > {}", rng.range(0, 2))
            } else {
                String::new()
            };
            format!(
                "select {} from {t1} x{} group by {}{having}",
                list.join(", "),
                where_(rng, &x),
                keys.join(", ")
            )
        }
        3 => {
            let types: Vec<Ty> = (0..rng.range(1, 2)).map(|_| *rng.pick(&TYPES)).collect();
            let a: Vec<String> = types.iter().map(|ty| expr(rng, &x, *ty, 1)).collect();
            let b: Vec<String> = types.iter().map(|ty| expr(rng, &x, *ty, 1)).collect();
            let op = rng.pick(&[
                "union",
                "union all",
                "intersect",
                "intersect all",
                "except",
                "except all",
            ]);
            format!(
                "select {} from {t1} x{} {op} select {} from {t2} x{}",
                a.join(", "),
                where_(rng, &x),
                b.join(", "),
                where_(rng, &x)
            )
        }
        4 => {
            let list = select_list(rng, &x);
            let order: Vec<String> = (1..=list.len())
                .map(|i| {
                    let dir = rng.pick(&["", " desc", " nulls first", " desc nulls last"]);
                    format!("{i}{dir}")
                })
                .collect();
            format!(
                "select {} from {t1} x{} order by {} limit {} offset {}",
                list.join(", "),
                where_(rng, &x),
                order.join(", "),
                rng.range(0, 10),
                rng.range(0, 3)
            )
        }
        5 => {
            let list = select_list(rng, &x);
            format!("select distinct {} from {t1} x{}", list.join(", "), where_(rng, &x))
        }
        6 => {
            let list = select_list(rng, &x);
            let y = columns("y");
            let inner = expr(rng, &y, Ty::Bool, 2);
            let test = match rng.below(5) {
                0 => format!("exists (select 1 from {t2} y where y.a = x.a and {inner})"),
                1 => format!("not exists (select 1 from {t2} y where y.e = x.e and {inner})"),
                2 => format!("x.a in (select y.a from {t2} y where {inner})"),
                3 => format!("x.a not in (select y.a from {t2} y where {inner})"),
                _ => format!("x.b > (select min(y.b) from {t2} y where y.e = x.e)"),
            };
            format!("select {} from {t1} x where {test}", list.join(", "))
        }
        _ => {
            let types: Vec<Ty> = (0..rng.range(1, 4)).map(|_| *rng.pick(&TYPES)).collect();
            let inner: Vec<String> = types
                .iter()
                .enumerate()
                .map(|(i, ty)| format!("{} as c{}", expr(rng, &x, *ty, 2), i + 1))
                .collect();
            let s: Vec<Column> = types
                .iter()
                .enumerate()
                .map(|(i, ty)| Column { table: "s".into(), name: format!("c{}", i + 1), ty: *ty })
                .collect();
            format!(
                "select s.* from (select {} from {t1} x{}) s{}",
                inner.join(", "),
                where_(rng, &x),
                where_(rng, &s)
            )
        }
    }
}

/// A logic check: two queries that must give the same rows on one server.
#[derive(Debug)]
struct Check {
    kind: &'static str,
    query: String,
    other: String,
}

fn checks(rng: &mut Rng, count: usize) -> Vec<Check> {
    let mut checks = Vec::new();
    for _ in 0..count {
        let t1 = *rng.pick(&TABLES);
        let t2 = *rng.pick(&TABLES);
        let join = rng.chance(40);
        let (from, scope) = if join {
            let mut xy = columns("x");
            xy.extend(columns("y"));
            (format!("{t1} x join {t2} y on x.a = y.a"), xy)
        } else {
            (format!("{t1} x"), columns("x"))
        };
        let p = expr(rng, &scope, Ty::Bool, 3);
        let parts = |select: &str, union: &str| {
            format!(
                "{select} from {from} where {p} {union} {select} from {from} where not ({p}) {union} {select} from {from} where ({p}) is null"
            )
        };
        checks.push(match rng.below(4) {
            0 => Check {
                kind: "tlp where",
                query: format!("select * from {from}"),
                other: parts("select *", "union all"),
            },
            1 => Check {
                kind: "tlp distinct",
                query: format!("select distinct x.e, x.a from {from}"),
                other: parts("select x.e, x.a", "union"),
            },
            2 => Check {
                kind: "tlp max",
                query: format!("select max(x.a) from {from}"),
                other: format!(
                    "select max(m) from ({}) s",
                    parts("select max(x.a) as m", "union all")
                ),
            },
            _ => Check {
                kind: "norec",
                query: format!("select count(*) from {from} where {p}"),
                other: format!(
                    "select coalesce(sum(case when {p} then 1 else 0 end), 0) from {from}"
                ),
            },
        });
    }
    checks
}

/// Runs the checks on one server in a new database and returns the number that failed.
fn run_checks(
    server: &Server,
    schema: &[String],
    checks: &[Check],
) -> Result<(usize, Json), String> {
    let mut admin =
        Client::connect(server, &Login::superuser("postgres")).map_err(|r| r.message)?;
    for sql in [
        format!("DROP DATABASE IF EXISTS {DATABASE} WITH (FORCE)"),
        format!("CREATE DATABASE {DATABASE} TEMPLATE template0"),
    ] {
        must(&mut admin, server, &sql)?;
    }
    let mut client = Client::connect(server, &Login::superuser(DATABASE)).map_err(|r| r.message)?;
    must(&mut client, server, "set statement_timeout = '10s'")?;
    for sql in schema {
        must(&mut client, server, sql)?;
    }
    let mut failures = Vec::new();
    let mut inconclusive = 0;
    for (i, check) in checks.iter().enumerate() {
        let a = client.simple(&check.query).map_err(|e| format!("{}: {e}", server.name))?;
        let b = client.simple(&check.other).map_err(|e| format!("{}: {e}", server.name))?;
        if failed(&a) || failed(&b) {
            inconclusive += 1;
            continue;
        }
        let (mut x, mut y) = (client::rows(&a), client::rows(&b));
        x.sort();
        y.sort();
        if x != y {
            failures.push(Json::object(vec![
                ("check", Json::Number(i as i64 + 1)),
                ("kind", Json::str(check.kind)),
                ("query", Json::str(&check.query)),
                ("other", Json::str(&check.other)),
                ("rows", Json::Number(x.len() as i64)),
                ("other_rows", Json::Number(y.len() as i64)),
            ]));
            println!(
                "{}: {} check {} fails:\n  {}\n  {}",
                server.name,
                check.kind,
                i + 1,
                check.query,
                check.other
            );
        }
    }
    println!(
        "logic checks on {}: {} run, {} fail, {inconclusive} not counted because a query failed",
        server.name,
        checks.len(),
        failures.len()
    );
    let n = failures.len();
    Ok((
        n,
        Json::object(vec![
            ("server", Json::str(&server.name)),
            ("checks", Json::Number(checks.len() as i64)),
            ("inconclusive", Json::Number(inconclusive)),
            ("failures", Json::Array(failures)),
        ]),
    ))
}

fn failed(reply: &[Frame]) -> bool {
    reply.iter().any(|f| f.tag == b'E')
}

fn must(client: &mut Client, server: &Server, sql: &str) -> Result<(), String> {
    let reply = client.simple(sql).map_err(|e| format!("{}: {e}", server.name))?;
    match reply.iter().find(|f| f.tag == b'E') {
        Some(error) => Err(format!("{}: {sql}: {}", server.name, client::error_text(error))),
        None => Ok(()),
    }
}

#[cfg(test)]
mod tests {
    use super::{Rng, VALUES, query, schema};

    #[test]
    fn the_same_seed_gives_the_same_statements() {
        let make = |seed| {
            let mut rng = Rng::new(seed);
            let mut out = schema(&mut rng);
            out.extend((0..50).map(|_| query(&mut rng)));
            out
        };
        assert_eq!(make(7), make(7));
        assert_ne!(make(7), make(8));
    }

    #[test]
    fn each_type_has_a_value() {
        for (typname, values) in VALUES {
            assert!(!values.is_empty(), "{typname}");
        }
    }
}
